# Generated by Django 4.2 on 2023-04-22 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fiicode', '0002_document_user_vacation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestVacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(default='pdf', max_length=255),
        ),
    ]
