# Generated by Django 4.2 on 2023-04-22 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiicode', '0003_requestvacation_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
    ]
