# Generated by Django 4.2 on 2023-04-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiicode', '0004_remove_document_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='userId',
            field=models.CharField(max_length=255),
        ),
    ]
