# Generated by Django 4.2 on 2023-04-22 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiicode', '0007_alter_vacation_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestvacation',
            name='description',
        ),
    ]
